name: "Deploy to NuGet"

on:
  push:
    tags:
    - 'v*'
    branches:
    - main

env:
  PROJECT_PATH: 'NugetPackageDemo/NugetPackageDemo.csproj'
  PACKAGE_OUTPUT_DIRECTORY: ${{ github.workspace }}/output
  NUGET_SOURCE_URL: 'https://api.nuget.org/v3/index.json'

jobs:
  deploy:
    name: 'Deploy'
    runs-on: 'ubuntu-latest'
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2

    - name: 'Install dotnet'
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: 'Restore packages'
      run: dotnet restore ${{ env.PROJECT_PATH }}

    - name: 'Build project'
      run: dotnet build ${{ env.PROJECT_PATH }} --no-restore --configuration Release
    
    - name: 'Pack project'
      run: dotnet pack ${{ env.PROJECT_PATH }}_kalyan --no-restore --no-build --configuration Release --include-symbols --output ${{ env.PACKAGE_OUTPUT_DIRECTORY }}
    
    - name: 'Print Secret'
      run: echo 'Hello' ${{ secrets.KALYAN_NUGET_SECRET }}

    - name: 'Push package'
      run: dotnet nuget push ${{ env.PACKAGE_OUTPUT_DIRECTORY }}/*.nupkg -k ${{ secrets.KALYAN_NUGET_SECRET }} -s ${{ env.NUGET_SOURCE_URL }}
      